### PR TITLE
Release v0.2.3

### PR DESCRIPTION
**Pull request by cosmo0920**
* Bump up nokogiri version to v0.12
* Bump up test-unit version to v3.4 for Ruby 3 compatibility

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

### CODE REVIEW

**Review by ashie — APPROVED** [review]

**Review by ashie — CHANGES_REQUESTED** [review]
Oops, CI seems to need update

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby x64-mingw32
    bundler x64-mingw32 was resolved to 2.0.2, which depends on
      ruby (>= 2.3.0) x64-mingw32
fluent-plugin-parser-winevt_xml x64-mingw32 was resolved to 0.2.3, which
depends on
nokogiri (>= 1.12.5, < 1.13) x64-mingw32 was resolved to 1.12.5, which
depends on
        ruby (>= 2.5, < 3.1.dev) x64-mingw32
    rake x64-mingw32 was resolved to 13.0.6, which depends on
      ruby (>= 2.2) x64-mingw32
```

**Comment by cosmo0920** [comment]
Yes, we need to migrate GItHub Actions.

We don't need to be continuing support Ruby 2.4.

**Comment by cosmo0920** [comment]
I removed Travis CI settings and disable building there.

**Comment by cosmo0920** [comment]
We got succeeded that CIs are green!

**Review by ashie — APPROVED** [review]

**Pull request merged**
