### PR TITLE
CI: Update Ruby

### PR DESCRIPTION
**Pull request by ashie**
And shorten labels to make easy to read on GitHub.

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Comment by ashie** [comment]
Failed on Ruby 3.1 Windows:

https://github.com/fluent/fluent-plugin-windows-eventlog/runs/4962066485?check_suite_focus=true

```
C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/fluentd-1.14.4/lib/fluent/plugin_helper/socket.rb:21:in `require': cannot load such file -- certstore (LoadError)
```

I'm not sure why but dependent gems on Windows aren't installed:
```
2022-01-27T05:46:08.1202909Z Fetching gem metadata from https://rubygems.org/......
2022-01-27T05:46:08.3238018Z Resolving dependencies...
2022-01-27T05:46:08.3316714Z Using rake 13.0.6
2022-01-27T05:46:08.3395051Z Using bundler 2.3.6
2022-01-27T05:46:08.3415592Z Fetching concurrent-ruby 1.1.9
2022-01-27T05:46:08.3418484Z Fetching cool.io 1.7.1
2022-01-27T05:46:08.3421715Z Fetching ffi 1.15.5 (x64-mingw-ucrt)
2022-01-27T05:46:08.3423207Z Fetching http_parser.rb 0.8.0
2022-01-27T05:46:08.4800311Z Installing cool.io 1.7.1 with native extensions
2022-01-27T05:46:08.4832021Z Installing ffi 1.15.5 (x64-mingw-ucrt)
2022-01-27T05:46:08.4915092Z Installing http_parser.rb 0.8.0 with native extensions
2022-01-27T05:46:08.4980020Z Installing concurrent-ruby 1.1.9
2022-01-27T05:46:09.5834976Z Fetching msgpack 1.4.4
2022-01-27T05:46:09.7017179Z Installing msgpack 1.4.4 with native extensions
2022-01-27T05:46:13.4405763Z Fetching sigdump 0.2.4
2022-01-27T05:46:13.4943794Z Fetching strptime 0.2.5
2022-01-27T05:46:13.5203617Z Installing sigdump 0.2.4
2022-01-27T05:46:13.6051041Z Fetching webrick 1.7.0
2022-01-27T05:46:13.6053307Z Installing strptime 0.2.5 with native extensions
2022-01-27T05:46:17.8737641Z Installing webrick 1.7.0
2022-01-27T05:46:45.0979639Z Fetching yajl-ruby 1.4.1
2022-01-27T05:46:49.4229934Z Installing yajl-ruby 1.4.1 with native extensions
2022-01-27T05:46:53.7863384Z Fetching mini_portile2 2.5.3
2022-01-27T05:46:53.7863832Z Using racc 1.6.0
2022-01-27T05:46:53.7864088Z Fetching winevt_c 0.9.3
2022-01-27T05:46:53.7864416Z Installing mini_portile2 2.5.3
2022-01-27T05:46:53.7864718Z Installing winevt_c 0.9.3 with native extensions
2022-01-27T05:46:53.7865092Z Using power_assert 2.0.1
2022-01-27T05:46:53.7865428Z Fetching win32-eventlog 0.6.7
2022-01-27T05:46:53.7865701Z Installing win32-eventlog 0.6.7
2022-01-27T05:46:54.1281173Z Fetching tzinfo 2.0.4
2022-01-27T05:46:54.1282769Z Fetching serverengine 2.2.5
2022-01-27T05:46:54.2047169Z Installing tzinfo 2.0.4
2022-01-27T05:46:54.7192007Z Installing serverengine 2.2.5
2022-01-27T05:46:54.8859707Z Fetching nokogiri 1.11.7
2022-01-27T05:46:55.5349874Z Installing nokogiri 1.11.7 with native extensions
2022-01-27T05:47:02.8131938Z Fetching test-unit 3.4.9
2022-01-27T05:47:02.8132351Z Installing test-unit 3.4.9
2022-01-27T05:47:02.8132628Z Fetching tzinfo-data 1.2021.5
2022-01-27T05:47:02.8132964Z Installing tzinfo-data 1.2021.5
2022-01-27T05:47:13.0743168Z Fetching fluentd 1.14.4
2022-01-27T05:47:13.2463882Z Installing fluentd 1.14.4
2022-01-27T05:47:14.7037349Z Using fluent-plugin-windows-eventlog 0.8.1 from source at `.`
2022-01-27T05:56:19.3442305Z Fetching fluent-plugin-parser-winevt_xml 0.2.2
2022-01-27T05:56:19.4010080Z Installing fluent-plugin-parser-winevt_xml 0.2.2
2022-01-27T05:56:19.4474049Z Bundle complete! 6 Gemfile dependencies, 24 gems now installed.
2022-01-27T05:56:19.4474703Z Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by ashie** [comment]
https://github.com/fluent/fluentd/pull/3613

**Comment by ashie** [comment]
I've released v1.14.4-x64-mingw-ucrt.
All tests are passed.

**Review by cosmo0920 — APPROVED** [review]
Ah, really good.

**Pull request merged**
